# micromuck-java
version: "v2"

system-name: "java-mm-bookstore"
resultsPath: "/home/vahid/Dropbox/data/swarm-manager-data/results/$SYSTEM_NAME/$WORKLOAD/$STRATEGY/" #TODO change this auto, also create folders auto
logDirectory: "/home/vahid/Desktop/projects/swarm-manager-data/logs"

dropbox-path: "/home/vahid/Dropbox/data/swarm-manager-data/cache"
docker-compose-file: "/home/vahid/Desktop/projects/micromuck-java/docker-compose.yml"
service-count: 5
stack-name: "jmm-bookstore"
host: "tcp://136.159.209.204:2375"

jaeger-host: "http://136.159.209.204:16686"
jaeger-root-service: "nginx"
jaeger-details-file-path: "/home/vahid/Desktop/projects/swarmmanager/formulas/java_mm_bookstore.yaml"
jaegerStorePath: "/home/vahid/Dropbox/data/swarm-manager-data/jaegers"

k6-script: "/home/vahid/Desktop/projects/micromuck-java/load-generator/booksotre-system/scripts/type1.js"
test-duration: 60
wait-after-load-test: 30 
available-cpu-count: 24
services-to-monitor: auth,books,gateway