resultsPath: "/home/vahid/Dropbox/data/swarm-manager-data/results/$WORKLOAD/single/" #TODO change this auto, also create folders auto
logDirectory: "/home/vahid/Desktop/projects/swarm-manager-data/logs"
jaegerStorePath: "/home/vahid/Dropbox/data/swarm-manager-data/jaegers"
dropbox-path: "/home/vahid/Dropbox/data/swarm-manager-data/cache"
docker-compose-file: "/home/vahid/Desktop/docker-compose-nodb.yml"
service-count: 4
stack-name: "bookstore"
host: "tcp://136.159.209.204:2375"
jaeger-host: "http://136.159.209.204:16686"
k6-script: "/home/vahid/Desktop/type8.js"
version: "v1"
test-duration: 60
wait-after-load-test: 30 
available-cpu-count: 24
services-to-monitor: auth,books,gateway