resultsPath: "/Users/vahid/Desktop/projects/swarm-manager-data/test"
logDirectory: "/Users/vahid/Desktop/projects/swarm-manager-data/logs"
jegerStorePath: "/Users/vahid/Desktop/projects/swarm-manager-data/jaegers"
