resultsPath: "/Users/vahid/Desktop/projects/swarm-manager-data/workloads/250_50_50"
logDirectory: "/Users/vahid/Desktop/projects/swarm-manager-data/logs"
jegerStorePath: "/Users/vahid/Desktop/projects/swarm-manager-data/jaegers"
