version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 8G
        reservations:
          cpus: "1"
          memory: 1G
###############################################
  servicea:
    image: vahidmostofi/micromuck-nodejs:v1
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 10080:10080
    depends_on: 
      - jaeger
    environment:
      - SERVICE_NAME=servicea
      - WORKER_COUNT=1
      - SEED=9
      - PORT=10080
      - MEAN_RESPONSE_TIMES={"req1":-1, "req2":-1, "req3":-1, "req4":-1, "req5":-1}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 3G
        reservations:
          cpus: "1"
          memory: 0.7G
###############################################
  serviceb:
    image: vahidmostofi/micromuck-nodejs:v1
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 10081:10081
    depends_on: 
      - jaeger
    environment:
      - SERVICE_NAME=serviceb
      - WORKER_COUNT=1
      - SEED=9
      - PORT=10081
      - MEAN_RESPONSE_TIMES={"req1":25, "req2":26, "req3":21, "req4":28, "req5":80}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 3G
        reservations:
          cpus: "1"
          memory: 0.7G
###############################################
  servicec:
    image: vahidmostofi/micromuck-nodejs:v1
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 10082:10082
    depends_on: 
      - jaeger
    environment:
      - SERVICE_NAME=servicec
      - WORKER_COUNT=1
      - SEED=9
      - PORT=10082
      - MEAN_RESPONSE_TIMES={"req1":20, "req2":16, "req3":21, "req4":23, "req5":83}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 3G
        reservations:
          cpus: "1"
          memory: 0.7G
###############################################
  serviced:
    image: vahidmostofi/micromuck-nodejs:v1
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 10083:10083
    depends_on: 
      - jaeger
    environment:
      - SERVICE_NAME=serviced
      - WORKER_COUNT=1
      - SEED=9
      - PORT=10083
      - MEAN_RESPONSE_TIMES={"req1":13,"req2":9,"req3":9,"req4":24,"req5":86}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 3G
        reservations:
          cpus: "1"
          memory: 0.7G
###############################################
  servicee:
    image: vahidmostofi/micromuck-nodejs:v1
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 10084:10084
    depends_on: 
      - jaeger
    environment:
      - SERVICE_NAME=servicee
      - WORKER_COUNT=1
      - SEED=9
      - PORT=10084
      - MEAN_RESPONSE_TIMES={"req1":17,"req2":20,"req3":8,"req4":26,"req5":10}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 3G
        reservations:
          cpus: "1"
          memory: 0.7G
###############################################
  servicef:
    image: vahidmostofi/micromuck-nodejs:v1
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 10085:10085
    depends_on: 
      - jaeger
    environment:
      - SERVICE_NAME=servicef
      - WORKER_COUNT=1
      - SEED=9
      - PORT=10085
      - MEAN_RESPONSE_TIMES={"req1":16,"req2":21,"req3":15,"req4":19,"req5":21}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 3G
        reservations:
          cpus: "1"
          memory: 0.7G