version: '3'

services:
  nginx:
    image: opentracing/nginx-opentracing
    restart: always
    volumes:
      - /home/vahid/workspace/ngingx/nginx.conf:/etc/nginx/nginx.conf
      - /home/vahid/workspace/ngingx/jaeger-config.json:/etc/jaeger-config.json
    expose:
      - "9080"
    ports:
      - "9080:9080"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 6G
        reservations:
          cpus: "1"
          memory: 3G
#################################################
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "5775:5775/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 8G
        reservations:
          cpus: "1"
          memory: 6G
  ################################################
  # db:
  #   container_name: bs_db
  #   image: mongo:3.4.24-xenial
  #   restart: always
  #   ports:
  #     - 27717:27017
  #   volumes:
  #     - /data/mongo:/data/db
  #   deploy:
  #     replicas: 1
  #     resources:
  #       limits:
  #         cpus: "1"
  #         memory: 10G
  #       reservations:
  #         cpus: "1"
  #         memory: 2G
  ################################################
  gateway:
    container_name: bs_gw
    build: './api-gateway'
    image: vahidmostofi/bookstore_gateway:nodb
    restart: always
    ports:
      - "9092:9080"
    depends_on:
      - auth
    environment: 
      - JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
      - JAEGER_AGENT_HOST=jaeger
      - WorkerCount=1
      - JWT_KEY=someKeyIsGoodAndSomeOfThemBNoGEo1ioD!
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 10G
        reservations:
          cpus: "1"
          memory: 2G
  ################################################
  auth:
    container_name: bs_auth
    build: './auth-service'
    image: vahidmostofi/bookstore_auth:nodb
    restart: always
    ports:
      - "3007:3007"
    environment:
      - JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
      - JAEGER_AGENT_HOST=jaeger
      - WorkerCount=1
      # - MONGODB_URL=mongodb://db:27017/bookstoreDB
      - JWT_KEY=someKeyIsGoodAndSomeOfThemBNoGEo1ioD!
      - PORT=3007
    # depends_on:
    #   - db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 10G
        reservations:
          cpus: "1"
          memory: 2G
  ################################################
  books:
    container_name: bs_books
    image: vahidmostofi/bookstore_books:nodb
    restart: always
    build: './book-service'
    ports:
      - "3009:3009"
    environment:
      - JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
      - JAEGER_AGENT_HOST=jaeger
      - WorkerCount=1
      # - MONGODB_URL=mongodb://db:27017/bookstoreDB
      - PORT=3009
    # depends_on:
    #   - db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 10G
        reservations:
          cpus: "1"
          memory: 2G
